Return error instead of panic on enum with 0 variants
Before PR 53:

    thread 'main' panicked at /git/tmp/serde-reflection/serde-reflection/src/de.rs:431:18:
    variant indexes must be a non-empty range 0..variants.len()

First draft of PR 53, debug mode (overflow checks):

    thread 'main' panicked at /git/tmp/serde-reflection/serde-reflection/src/de.rs:435:42:
    attempt to subtract with overflow

First draft of PR 53, release mode:

    Failed to deserialize value: "invalid value: integer `0`, expected variant index 0 <= i < 0"

This commit:

    Not supported: deserialize_enum with 0 variants